name: 'Run Tests'
on:
  pull_requests:
    branches:
      - main

jobs:
  run-tests:
    runs-on:
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          cd ray-tracer
          mkdir build && cd build
          cmake -G Ninja ..
          cmake --build . --target test
